// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgressqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveReviewRequest(ctx context.Context, arg ApproveReviewRequestParams) (ApproveReviewRequestRow, error)
	AssignRolePermissions(ctx context.Context, arg AssignRolePermissionsParams) error
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateGuardrailViolation(ctx context.Context, arg CreateGuardrailViolationParams) (GuardrailViolation, error)
	CreateQuota(ctx context.Context, arg CreateQuotaParams) (Quota, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReviewRequest(ctx context.Context, arg CreateReviewRequestParams) (ReviewRequest, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteQuota(ctx context.Context, arg DeleteQuotaParams) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetAuditEventBySeq(ctx context.Context, arg GetAuditEventBySeqParams) (AuditEvent, error)
	GetAuditEvents(ctx context.Context, arg GetAuditEventsParams) ([]AuditEvent, error)
	GetQuotaByScope(ctx context.Context, arg GetQuotaByScopeParams) (Quota, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetReviewRequestByID(ctx context.Context, arg GetReviewRequestByIDParams) (ReviewRequest, error)
	GetReviewRequestByTokenHash(ctx context.Context, tokenHash []byte) (GetReviewRequestByTokenHashRow, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRolePermissions(ctx context.Context, arg GetRolePermissionsParams) ([]string, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	ListActiveRefreshTokens(ctx context.Context, arg ListActiveRefreshTokensParams) ([]RefreshToken, error)
	ListGuardrailViolations(ctx context.Context, arg ListGuardrailViolationsParams) ([]GuardrailViolation, error)
	ListQuotasByTenant(ctx context.Context, tenantID uuid.UUID) ([]Quota, error)
	ListReviewRequests(ctx context.Context, arg ListReviewRequestsParams) ([]ListReviewRequestsRow, error)
	ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error)
	RejectReviewRequest(ctx context.Context, arg RejectReviewRequestParams) (RejectReviewRequestRow, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	RevokeRolePermissions(ctx context.Context, arg RevokeRolePermissionsParams) error
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RotateRefreshTokenRow, error)
	SweepExpiredReviews(ctx context.Context, tenantID uuid.UUID) error
	UpdateQuota(ctx context.Context, arg UpdateQuotaParams) (Quota, error)
	UpdateRefreshTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
