// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChatCompletionRequestMessagesRole.
const (
	ChatCompletionRequestMessagesRoleAssistant ChatCompletionRequestMessagesRole = "assistant"
	ChatCompletionRequestMessagesRoleSystem    ChatCompletionRequestMessagesRole = "system"
	ChatCompletionRequestMessagesRoleTool      ChatCompletionRequestMessagesRole = "tool"
	ChatCompletionRequestMessagesRoleUser      ChatCompletionRequestMessagesRole = "user"
)

// Valid indicates whether the value is a known member of the ChatCompletionRequestMessagesRole enum.
func (e ChatCompletionRequestMessagesRole) Valid() bool {
	switch e {
	case ChatCompletionRequestMessagesRoleAssistant:
		return true
	case ChatCompletionRequestMessagesRoleSystem:
		return true
	case ChatCompletionRequestMessagesRoleTool:
		return true
	case ChatCompletionRequestMessagesRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for ChatCompletionResponseChoicesFinishReason.
const (
	ContentFilter ChatCompletionResponseChoicesFinishReason = "content_filter"
	Length        ChatCompletionResponseChoicesFinishReason = "length"
	Stop          ChatCompletionResponseChoicesFinishReason = "stop"
	ToolCalls     ChatCompletionResponseChoicesFinishReason = "tool_calls"
)

// Valid indicates whether the value is a known member of the ChatCompletionResponseChoicesFinishReason enum.
func (e ChatCompletionResponseChoicesFinishReason) Valid() bool {
	switch e {
	case ContentFilter:
		return true
	case Length:
		return true
	case Stop:
		return true
	case ToolCalls:
		return true
	default:
		return false
	}
}

// Defines values for QuotaRequestScope.
const (
	QuotaRequestScopeRole   QuotaRequestScope = "role"
	QuotaRequestScopeTenant QuotaRequestScope = "tenant"
	QuotaRequestScopeUser   QuotaRequestScope = "user"
)

// Valid indicates whether the value is a known member of the QuotaRequestScope enum.
func (e QuotaRequestScope) Valid() bool {
	switch e {
	case QuotaRequestScopeRole:
		return true
	case QuotaRequestScopeTenant:
		return true
	case QuotaRequestScopeUser:
		return true
	default:
		return false
	}
}

// Defines values for QuotaResponseScope.
const (
	QuotaResponseScopeRole   QuotaResponseScope = "role"
	QuotaResponseScopeTenant QuotaResponseScope = "tenant"
	QuotaResponseScopeUser   QuotaResponseScope = "user"
)

// Valid indicates whether the value is a known member of the QuotaResponseScope enum.
func (e QuotaResponseScope) Valid() bool {
	switch e {
	case QuotaResponseScopeRole:
		return true
	case QuotaResponseScopeTenant:
		return true
	case QuotaResponseScopeUser:
		return true
	default:
		return false
	}
}

// Defines values for ReviewResponseStatus.
const (
	ReviewResponseStatusAPPROVED ReviewResponseStatus = "APPROVED"
	ReviewResponseStatusEXECUTED ReviewResponseStatus = "EXECUTED"
	ReviewResponseStatusEXPIRED  ReviewResponseStatus = "EXPIRED"
	ReviewResponseStatusPENDING  ReviewResponseStatus = "PENDING"
	ReviewResponseStatusREJECTED ReviewResponseStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ReviewResponseStatus enum.
func (e ReviewResponseStatus) Valid() bool {
	switch e {
	case ReviewResponseStatusAPPROVED:
		return true
	case ReviewResponseStatusEXECUTED:
		return true
	case ReviewResponseStatusEXPIRED:
		return true
	case ReviewResponseStatusPENDING:
		return true
	case ReviewResponseStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for TenantResponseStatus.
const (
	TenantResponseStatusActive    TenantResponseStatus = "active"
	TenantResponseStatusSuspended TenantResponseStatus = "suspended"
)

// Valid indicates whether the value is a known member of the TenantResponseStatus enum.
func (e TenantResponseStatus) Valid() bool {
	switch e {
	case TenantResponseStatusActive:
		return true
	case TenantResponseStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseStatus.
const (
	UserResponseStatusActive    UserResponseStatus = "active"
	UserResponseStatusDeleted   UserResponseStatus = "deleted"
	UserResponseStatusSuspended UserResponseStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserResponseStatus enum.
func (e UserResponseStatus) Valid() bool {
	switch e {
	case UserResponseStatusActive:
		return true
	case UserResponseStatusDeleted:
		return true
	case UserResponseStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ListTenantsParamsStatus.
const (
	ListTenantsParamsStatusActive    ListTenantsParamsStatus = "active"
	ListTenantsParamsStatusSuspended ListTenantsParamsStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ListTenantsParamsStatus enum.
func (e ListTenantsParamsStatus) Valid() bool {
	switch e {
	case ListTenantsParamsStatusActive:
		return true
	case ListTenantsParamsStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsStatus.
const (
	ListUsersParamsStatusActive    ListUsersParamsStatus = "active"
	ListUsersParamsStatusDeleted   ListUsersParamsStatus = "deleted"
	ListUsersParamsStatusSuspended ListUsersParamsStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ListUsersParamsStatus enum.
func (e ListUsersParamsStatus) Valid() bool {
	switch e {
	case ListUsersParamsStatusActive:
		return true
	case ListUsersParamsStatusDeleted:
		return true
	case ListUsersParamsStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ListReviewsParamsStatus.
const (
	ListReviewsParamsStatusAPPROVED ListReviewsParamsStatus = "APPROVED"
	ListReviewsParamsStatusEXECUTED ListReviewsParamsStatus = "EXECUTED"
	ListReviewsParamsStatusEXPIRED  ListReviewsParamsStatus = "EXPIRED"
	ListReviewsParamsStatusPENDING  ListReviewsParamsStatus = "PENDING"
	ListReviewsParamsStatusREJECTED ListReviewsParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ListReviewsParamsStatus enum.
func (e ListReviewsParamsStatus) Valid() bool {
	switch e {
	case ListReviewsParamsStatusAPPROVED:
		return true
	case ListReviewsParamsStatusEXECUTED:
		return true
	case ListReviewsParamsStatusEXPIRED:
		return true
	case ListReviewsParamsStatusPENDING:
		return true
	case ListReviewsParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// ApproveRequest defines model for ApproveRequest.
type ApproveRequest struct {
	// Token Opaque review token (returned at creation)
	Token string `json:"token"`
}

// ChatCompletionRequest defines model for ChatCompletionRequest.
type ChatCompletionRequest struct {
	MaxTokens *int `json:"max_tokens,omitempty"`
	Messages  []struct {
		Content    string                            `json:"content"`
		Role       ChatCompletionRequestMessagesRole `json:"role"`
		ToolCallId *string                           `json:"tool_call_id,omitempty"`
		ToolCalls  *[]map[string]interface{}         `json:"tool_calls,omitempty"`
	} `json:"messages"`

	// Model Example: gpt-4o-mini
	Model       string   `json:"model"`
	Stream      *bool    `json:"stream,omitempty"`
	Temperature *float32 `json:"temperature,omitempty"`
}

// ChatCompletionRequestMessagesRole defines model for ChatCompletionRequest.Messages.Role.
type ChatCompletionRequestMessagesRole string

// ChatCompletionResponse defines model for ChatCompletionResponse.
type ChatCompletionResponse struct {
	Choices *[]struct {
		FinishReason *ChatCompletionResponseChoicesFinishReason `json:"finish_reason,omitempty"`
		Index        *int                                       `json:"index,omitempty"`
		Message      *struct {
			Content *string `json:"content,omitempty"`
			Role    *string `json:"role,omitempty"`
		} `json:"message,omitempty"`
	} `json:"choices,omitempty"`
	Created *int `json:"created,omitempty"`

	// Id Example: chatcmpl-123
	Id    *string `json:"id,omitempty"`
	Model *string `json:"model,omitempty"`

	// Object Example: chat.completion
	Object *string `json:"object,omitempty"`
	Usage  *struct {
		CompletionTokens *int `json:"completion_tokens,omitempty"`
		PromptTokens     *int `json:"prompt_tokens,omitempty"`
		TotalTokens      *int `json:"total_tokens,omitempty"`
	} `json:"usage,omitempty"`
}

// ChatCompletionResponseChoicesFinishReason defines model for ChatCompletionResponse.Choices.FinishReason.
type ChatCompletionResponseChoicesFinishReason string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Example: unauthorized
	Error string `json:"error"`

	// Message Example: Invalid or expired token
	Message *string `json:"message,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Example: admin@acme.com
	Email openapi_types.Email `json:"email"`

	// Password Example: strong-password
	Password string `json:"password"`

	// TenantId Example: 550e8400-e29b-41d4-a716-446655440000
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
	AccessToken string `json:"access_token"`

	// ExpiresIn Example: 900
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Example: dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4...
	RefreshToken string `json:"refresh_token"`
}

// PermissionRequest defines model for PermissionRequest.
type PermissionRequest struct {
	// Action Example: call
	Action string `json:"action"`

	// Description Example: Call LLM models
	Description *string `json:"description,omitempty"`

	// Resource Example: models
	Resource string `json:"resource"`
}

// PermissionResponse defines model for PermissionResponse.
type PermissionResponse struct {
	Action      *string             `json:"action,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Resource    *string             `json:"resource,omitempty"`
}

// QuotaRequest defines model for QuotaRequest.
type QuotaRequest struct {
	// RequestsPerMin Example: 60
	RequestsPerMin int                `json:"requests_per_min"`
	Scope          QuotaRequestScope  `json:"scope"`
	ScopeId        openapi_types.UUID `json:"scope_id"`

	// TokensPerMin Example: 10000
	TokensPerMin int `json:"tokens_per_min"`

	// ToolExecsPerMin Example: 30
	ToolExecsPerMin int `json:"tool_execs_per_min"`
}

// QuotaRequestScope defines model for QuotaRequest.Scope.
type QuotaRequestScope string

// QuotaResponse defines model for QuotaResponse.
type QuotaResponse struct {
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	RequestsPerMin  *int                `json:"requests_per_min,omitempty"`
	Scope           *QuotaResponseScope `json:"scope,omitempty"`
	ScopeId         *openapi_types.UUID `json:"scope_id,omitempty"`
	TenantId        *openapi_types.UUID `json:"tenant_id,omitempty"`
	TokensPerMin    *int                `json:"tokens_per_min,omitempty"`
	ToolExecsPerMin *int                `json:"tool_execs_per_min,omitempty"`
	UpdatedAt       *time.Time          `json:"updated_at,omitempty"`
}

// QuotaResponseScope defines model for QuotaResponse.Scope.
type QuotaResponseScope string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	// Action Example: tool:execute
	Action string `json:"action"`

	// Payload Example: {"args":{"content":"hello","path":"/tmp/test.txt"},"tool":"file_write"}
	Payload map[string]interface{} `json:"payload"`
}

// ReviewResponse defines model for ReviewResponse.
type ReviewResponse struct {
	Action      *string                 `json:"action,omitempty"`
	CreatedAt   *time.Time              `json:"created_at,omitempty"`
	DecidedAt   *time.Time              `json:"decided_at,omitempty"`
	DecidedBy   *openapi_types.UUID     `json:"decided_by,omitempty"`
	ExpiresAt   *time.Time              `json:"expires_at,omitempty"`
	Id          *openapi_types.UUID     `json:"id,omitempty"`
	Payload     *map[string]interface{} `json:"payload,omitempty"`
	RequesterId *openapi_types.UUID     `json:"requester_id,omitempty"`
	Status      *ReviewResponseStatus   `json:"status,omitempty"`
	TenantId    *openapi_types.UUID     `json:"tenant_id,omitempty"`
}

// ReviewResponseStatus defines model for ReviewResponse.Status.
type ReviewResponseStatus string

// RoleRequest defines model for RoleRequest.
type RoleRequest struct {
	// Description Example: Can execute tools and call models
	Description *string `json:"description,omitempty"`

	// Name Example: operator
	Name string `json:"name"`
}

// RoleResponse defines model for RoleResponse.
type RoleResponse struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Ip         *string             `json:"ip,omitempty"`
	LastUsedAt *time.Time          `json:"last_used_at,omitempty"`
	UserAgent  *string             `json:"user_agent,omitempty"`
	UserId     *openapi_types.UUID `json:"user_id,omitempty"`
}

// TenantRequest defines model for TenantRequest.
type TenantRequest struct {
	// Name Example: Acme Inc
	Name string `json:"name"`
}

// TenantResponse defines model for TenantResponse.
type TenantResponse struct {
	CreatedAt *time.Time            `json:"created_at,omitempty"`
	Id        *openapi_types.UUID   `json:"id,omitempty"`
	Name      *string               `json:"name,omitempty"`
	Status    *TenantResponseStatus `json:"status,omitempty"`
}

// TenantResponseStatus defines model for TenantResponse.Status.
type TenantResponseStatus string

// UserRequest defines model for UserRequest.
type UserRequest struct {
	// Email Example: user@acme.com
	Email openapi_types.Email `json:"email"`

	// Password Example: strong-password
	Password string `json:"password"`

	// Role Example: operator
	Role *string `json:"role,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt *time.Time           `json:"created_at,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	Id        *openapi_types.UUID  `json:"id,omitempty"`
	Status    *UserResponseStatus  `json:"status,omitempty"`
	TenantId  *openapi_types.UUID  `json:"tenant_id,omitempty"`
	UpdatedAt *time.Time           `json:"updated_at,omitempty"`
}

// UserResponseStatus defines model for UserResponse.Status.
type UserResponseStatus string

// ListTenantsParams defines parameters for ListTenants.
type ListTenantsParams struct {
	Status *ListTenantsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                     `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTenantsParamsStatus defines parameters for ListTenants.
type ListTenantsParamsStatus string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Status *ListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                   `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParamsStatus defines parameters for ListUsers.
type ListUsersParamsStatus string

// ListReviewsParams defines parameters for ListReviews.
type ListReviewsParams struct {
	Status *ListReviewsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                     `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListReviewsParamsStatus defines parameters for ListReviews.
type ListReviewsParamsStatus string

// CreatePermissionJSONRequestBody defines body for CreatePermission for application/json ContentType.
type CreatePermissionJSONRequestBody = PermissionRequest

// CreateQuotaJSONRequestBody defines body for CreateQuota for application/json ContentType.
type CreateQuotaJSONRequestBody = QuotaRequest

// UpdateQuotaJSONRequestBody defines body for UpdateQuota for application/json ContentType.
type UpdateQuotaJSONRequestBody = QuotaRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleRequest

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = TenantRequest

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = TenantRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// ChatCompletionsJSONRequestBody defines body for ChatCompletions for application/json ContentType.
type ChatCompletionsJSONRequestBody = ChatCompletionRequest

// CreateReviewJSONRequestBody defines body for CreateReview for application/json ContentType.
type CreateReviewJSONRequestBody = ReviewRequest

// ApproveReviewJSONRequestBody defines body for ApproveReview for application/json ContentType.
type ApproveReviewJSONRequestBody = ApproveRequest

// RejectReviewJSONRequestBody defines body for RejectReview for application/json ContentType.
type RejectReviewJSONRequestBody = ApproveRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListPermissions List permissions
	// (GET /admin/permissions)
	ListPermissions(w http.ResponseWriter, r *http.Request)
	// CreatePermission Create permission
	// (POST /admin/permissions)
	CreatePermission(w http.ResponseWriter, r *http.Request)
	// ListQuotas List quotas
	// (GET /admin/quotas)
	ListQuotas(w http.ResponseWriter, r *http.Request)
	// CreateQuota Create quota
	// (POST /admin/quotas)
	CreateQuota(w http.ResponseWriter, r *http.Request)
	// DeleteQuota Delete quota
	// (DELETE /admin/quotas/{id})
	DeleteQuota(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetQuota Get quota
	// (GET /admin/quotas/{id})
	GetQuota(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateQuota Update quota
	// (PATCH /admin/quotas/{id})
	UpdateQuota(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListRoles List roles
	// (GET /admin/roles)
	ListRoles(w http.ResponseWriter, r *http.Request)
	// CreateRole Create role
	// (POST /admin/roles)
	CreateRole(w http.ResponseWriter, r *http.Request)
	// DeleteRole Delete role
	// (DELETE /admin/roles/{id})
	DeleteRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetRole Get role
	// (GET /admin/roles/{id})
	GetRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateRole Update role
	// (PATCH /admin/roles/{id})
	UpdateRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListTenants List tenants (Super Admin only)
	// (GET /admin/tenants)
	ListTenants(w http.ResponseWriter, r *http.Request, params ListTenantsParams)
	// CreateTenant Create tenant (Super Admin only)
	// (POST /admin/tenants)
	CreateTenant(w http.ResponseWriter, r *http.Request)
	// DeleteTenant Delete tenant (Super Admin only)
	// (DELETE /admin/tenants/{id})
	DeleteTenant(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetTenant Get tenant (Super Admin only)
	// (GET /admin/tenants/{id})
	GetTenant(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateTenant Update tenant (Super Admin only)
	// (PATCH /admin/tenants/{id})
	UpdateTenant(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListUsers List users in tenant
	// (GET /admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// CreateUser Create user in tenant
	// (POST /admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser Delete user
	// (DELETE /admin/users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetUser Get user
	// (GET /admin/users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateUser Update user
	// (PATCH /admin/users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Login User login
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Logout (revoke current session)
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Refresh Refresh access token
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// RevokeAllSessions Revoke all sessions
	// (DELETE /auth/sessions)
	RevokeAllSessions(w http.ResponseWriter, r *http.Request)
	// ListSessions List active sessions
	// (GET /auth/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// ChatCompletions Chat completions
	// (POST /chat/completions)
	ChatCompletions(w http.ResponseWriter, r *http.Request)
	// Health Liveness probe
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// Ready Readiness probe
	// (GET /ready)
	Ready(w http.ResponseWriter, r *http.Request)
	// ListReviews List review requests
	// (GET /reviews)
	ListReviews(w http.ResponseWriter, r *http.Request, params ListReviewsParams)
	// CreateReview Create review request
	// (POST /reviews)
	CreateReview(w http.ResponseWriter, r *http.Request)
	// GetReview Get review request
	// (GET /reviews/{id})
	GetReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ApproveReview Approve review request
	// (POST /reviews/{id}/approve)
	ApproveReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// RejectReview Reject review request
	// (POST /reviews/{id}/reject)
	RejectReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// StreamReview Stream review status (SSE)
	// (GET /reviews/{id}/stream)
	StreamReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListPermissions List permissions
// (GET /admin/permissions)
func (_ Unimplemented) ListPermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreatePermission Create permission
// (POST /admin/permissions)
func (_ Unimplemented) CreatePermission(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListQuotas List quotas
// (GET /admin/quotas)
func (_ Unimplemented) ListQuotas(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateQuota Create quota
// (POST /admin/quotas)
func (_ Unimplemented) CreateQuota(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteQuota Delete quota
// (DELETE /admin/quotas/{id})
func (_ Unimplemented) DeleteQuota(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetQuota Get quota
// (GET /admin/quotas/{id})
func (_ Unimplemented) GetQuota(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateQuota Update quota
// (PATCH /admin/quotas/{id})
func (_ Unimplemented) UpdateQuota(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRoles List roles
// (GET /admin/roles)
func (_ Unimplemented) ListRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateRole Create role
// (POST /admin/roles)
func (_ Unimplemented) CreateRole(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteRole Delete role
// (DELETE /admin/roles/{id})
func (_ Unimplemented) DeleteRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRole Get role
// (GET /admin/roles/{id})
func (_ Unimplemented) GetRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateRole Update role
// (PATCH /admin/roles/{id})
func (_ Unimplemented) UpdateRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTenants List tenants (Super Admin only)
// (GET /admin/tenants)
func (_ Unimplemented) ListTenants(w http.ResponseWriter, r *http.Request, params ListTenantsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateTenant Create tenant (Super Admin only)
// (POST /admin/tenants)
func (_ Unimplemented) CreateTenant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteTenant Delete tenant (Super Admin only)
// (DELETE /admin/tenants/{id})
func (_ Unimplemented) DeleteTenant(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTenant Get tenant (Super Admin only)
// (GET /admin/tenants/{id})
func (_ Unimplemented) GetTenant(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateTenant Update tenant (Super Admin only)
// (PATCH /admin/tenants/{id})
func (_ Unimplemented) UpdateTenant(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUsers List users in tenant
// (GET /admin/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateUser Create user in tenant
// (POST /admin/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteUser Delete user
// (DELETE /admin/users/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUser Get user
// (GET /admin/users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateUser Update user
// (PATCH /admin/users/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login User login
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Logout (revoke current session)
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Refresh access token
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RevokeAllSessions Revoke all sessions
// (DELETE /auth/sessions)
func (_ Unimplemented) RevokeAllSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListSessions List active sessions
// (GET /auth/sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ChatCompletions Chat completions
// (POST /chat/completions)
func (_ Unimplemented) ChatCompletions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Liveness probe
// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ready Readiness probe
// (GET /ready)
func (_ Unimplemented) Ready(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListReviews List review requests
// (GET /reviews)
func (_ Unimplemented) ListReviews(w http.ResponseWriter, r *http.Request, params ListReviewsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateReview Create review request
// (POST /reviews)
func (_ Unimplemented) CreateReview(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReview Get review request
// (GET /reviews/{id})
func (_ Unimplemented) GetReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApproveReview Approve review request
// (POST /reviews/{id}/approve)
func (_ Unimplemented) ApproveReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RejectReview Reject review request
// (POST /reviews/{id}/reject)
func (_ Unimplemented) RejectReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StreamReview Stream review status (SSE)
// (GET /reviews/{id}/stream)
func (_ Unimplemented) StreamReview(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPermissions operation middleware
func (siw *ServerInterfaceWrapper) ListPermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePermission operation middleware
func (siw *ServerInterfaceWrapper) CreatePermission(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePermission(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQuotas operation middleware
func (siw *ServerInterfaceWrapper) ListQuotas(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQuotas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuota operation middleware
func (siw *ServerInterfaceWrapper) CreateQuota(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuota(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuota operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuota(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuota(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuota operation middleware
func (siw *ServerInterfaceWrapper) GetQuota(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuota(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateQuota operation middleware
func (siw *ServerInterfaceWrapper) UpdateQuota(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateQuota(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoles operation middleware
func (siw *ServerInterfaceWrapper) ListRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRole operation middleware
func (siw *ServerInterfaceWrapper) CreateRole(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRole(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRole operation middleware
func (siw *ServerInterfaceWrapper) DeleteRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRole operation middleware
func (siw *ServerInterfaceWrapper) GetRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTenants operation middleware
func (siw *ServerInterfaceWrapper) ListTenants(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTenantsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenants(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTenant operation middleware
func (siw *ServerInterfaceWrapper) DeleteTenant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTenant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTenant operation middleware
func (siw *ServerInterfaceWrapper) UpdateTenant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTenant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAllSessions operation middleware
func (siw *ServerInterfaceWrapper) RevokeAllSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAllSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChatCompletions operation middleware
func (siw *ServerInterfaceWrapper) ChatCompletions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChatCompletions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReviews operation middleware
func (siw *ServerInterfaceWrapper) ListReviews(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReviewsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReviews(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReview operation middleware
func (siw *ServerInterfaceWrapper) CreateReview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReview operation middleware
func (siw *ServerInterfaceWrapper) GetReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveReview operation middleware
func (siw *ServerInterfaceWrapper) ApproveReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectReview operation middleware
func (siw *ServerInterfaceWrapper) RejectReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamReview operation middleware
func (siw *ServerInterfaceWrapper) StreamReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.Ready)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/sessions", wrapper.RevokeAllSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/tenants", wrapper.ListTenants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/tenants", wrapper.CreateTenant)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/tenants/{id}", wrapper.DeleteTenant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/tenants/{id}", wrapper.GetTenant)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/tenants/{id}", wrapper.UpdateTenant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/users/{id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/users/{id}", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/roles", wrapper.ListRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/roles", wrapper.CreateRole)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/roles/{id}", wrapper.DeleteRole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/roles/{id}", wrapper.GetRole)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/roles/{id}", wrapper.UpdateRole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/permissions", wrapper.ListPermissions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/permissions", wrapper.CreatePermission)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/quotas", wrapper.ListQuotas)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/quotas", wrapper.CreateQuota)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/quotas/{id}", wrapper.DeleteQuota)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/quotas/{id}", wrapper.GetQuota)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/quotas/{id}", wrapper.UpdateQuota)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reviews", wrapper.ListReviews)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reviews", wrapper.CreateReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reviews/{id}", wrapper.GetReview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reviews/{id}/approve", wrapper.ApproveReview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reviews/{id}/reject", wrapper.RejectReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reviews/{id}/stream", wrapper.StreamReview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/chat/completions", wrapper.ChatCompletions)
	})

	return r
}
